// 'use client'
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// // import Navbar from "./components/Navbar";
// // import CartProvider from "./components/CartProvider.server";
// // import CartProvider from "./components/Providers";
// import CartProvider from "./components/CartProvider.server";
// // import ShoppingCartModal from "./components/ShoppingCartModal";


// import dynamic from 'next/dynamic'
 
// const Navbar = dynamic(() => import('./components/Navbar'), { ssr: false })
// const ShoppingCartModal = dynamic(() => import('./components/ShoppingCartModal'), { ssr: false })

// const inter = Inter({ subsets: ["latin"] });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//     <CartProvider> 
//           <Navbar />
//           <ShoppingCartModal />
//           {children}
//           </CartProvider>
      
//       </body>
//     </html>
//   );
// }
'use client'
// RootLayout.tsx
import React, { useEffect, useState } from 'react';
import CartProvider from "./components/Providers";
// import CartProvider from './components/CartProvider.server';
import Navbar from './components/Navbar';
import { client } from './lib/sanity';
import "./globals.css";
import ShoppingCartModal from './components/ShoppingCartModal';
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const [data, setData] = useState<Data | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const query = "*[_type == 'logoImage'][0]";
        const result = await client.fetch(query);
        setData(result);
      } catch (error) {
        console.error('Error:', error);
      }
    };

    fetchData();
  }, []);

  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Navbar />
          <ShoppingCartModal />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}

interface Data {
  imageField: string;
   }

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import CartProvider from "./components/Providers";
// import Navbar from "./components/Navbar";
// import ShoppingCartModal from "./components/ShoppingCartModal";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <CartProvider>
//           <Navbar />
//           <ShoppingCartModal />
//           {children}
//         </CartProvider>
//       </body>
//     </html>
//   );
// }